### ISSUE TITLE
Problem in running aspire

### ISSUE THREAD

**Issue by suchitkumar** [korbinian90/ASPIRE#1]
Hello

I tried to run the aspire_custom.m file and i got the following error. Please check and help me how to solve this error.
Thank you

Error:

>> aspire_custom
Warning: Directory already exists. 
> In aspire>setupFolder (line 157)
  In aspire (line 4)
  In aspire_custom (line 35) 
There are 2 echoes and 32 channels
calculating slice: 1
Undefined function or variable 'centre_and_save_nii'.

Error in FlexibleStorage/saveAndCenter (line 122)
            centre_and_save_nii(image_nii, path, image_nii.hdr.dime.pixdim);

Error in FlexibleStorage/write (line 54)
                    self.saveAndCenter(image, filePath);

Error in aspire>allSteps (line 106)
    storage.write(combined_phase, 'combined_phase');

Error in aspire>allPipelines (line 45)
            allSteps(data, i);

Error in aspire (line 10)
    allPipelines(data);

Error in aspire_custom (line 35)
aspire(data);

**Comment by korbinian90** [comment]
Hi suchitkumar,
That is strange... the function centre_and_save_nii is not found. It is located in the folder 'dependencies', which should be automatically added to the path, when running aspire_custom.m (that happens in aspire_startup.m).

You can try to add the dependencies folder to the Matlab path and then try to run aspire_custom.m again.
Please report back, if it still crashes

**Comment by suchitkumar** [comment]
Hello
Thank you for your quick response. 
Yes, i checked the dependencies folder, last time when i downloaded, few files were missing.
Now i have downloaded the latest files and its running well now. 
Just one question, how well do you think this phase combination method will work on MR thermometry specially proton frequency shift method (PRF) which measure temperature difference based on the phase information?
Thank you

**Comment by korbinian90** [comment]
Great, that it works now and sorry that I forgot to add some files in the previous version!

You can definately use ASPIRE, if you have at least dual echo scans and TE2 = 2 * TE1.

From what I understand about PRF, you calculate a phase difference from two timepoints to estimate the temperature difference. I guess the direct approach would be to calculate a hermitian inner product on the seperate channel images to get the phase difference.
So I don't think you would get a big difference or improvement when calculating the phase difference from ASPIRE-combined images.
(Proper online phase combination could be beneficial though, as it avoids the need for seperate channel export)
